import { z } from 'zod'
import type { CrudFormConfig, CrudTableColumn } from '@/types/crud'
import { formatReferenceLabel, type RcmReferenceOptions } from '@/models/rcmReferenceOptions'
import type { Report, ReportCreatePayload, ReportFormValues } from '@/types/report'

export const reportApiDetails = {
  endpoint: '/rcm/reports',
  filterQueryParam: 'filter',
  responseDataPath: 'data',
  responseTotalPath: 'meta.total',
} as const

export const reportFormSchema = z.object({
  _id: z.string().optional(),
  reportName: z.string().trim(),
  reportType: z.string().trim(),
  dateFrom: z.date().nullable(),
  dateTo: z.date().nullable(),
  payerId: z.string().trim(),
  providerId: z.string().trim(),
  facilityId: z.string().trim(),
  generatedBy: z.string().trim(),
  generatedAt: z.date().nullable(),
  exportFormat: z.string().trim(),
  active: z.boolean(),
}) as z.ZodType<ReportFormValues>

export const reportDefaultValues: ReportFormValues = {
  _id: '',
  reportName: '',
  reportType: '',
  dateFrom: null,
  dateTo: null,
  payerId: '',
  providerId: '',
  facilityId: '',
  generatedBy: '',
  generatedAt: null,
  exportFormat: '',
  active: true,
}

export function createReportFormConfig(
  referenceOptions: RcmReferenceOptions = {},
): CrudFormConfig<ReportFormValues> {
  void referenceOptions
  return {
    schema: reportFormSchema,
    defaultValues: reportDefaultValues,
    columns: 2,
    fields: [
      {
        name: '_id',
        label: 'ID',
        type: 'hidden',
      },
    {
      name: 'reportName',
      label: 'report Name',
      type: 'text',
      placeholder: 'report Name',
    },
    {
      name: 'reportType',
      label: 'report Type',
      type: 'text',
      placeholder: 'report Type',
    },
    {
      name: 'dateFrom',
      label: 'date From',
      type: 'date',
      date: {
        showButtonBar: true,
      },
    },
    {
      name: 'dateTo',
      label: 'date To',
      type: 'date',
      date: {
        showButtonBar: true,
      },
    },
    {
      name: 'payerId',
      label: 'payer ID',
      type: 'autocomplete',
      placeholder: 'payer ID',
      options: referenceOptions.payers ?? [],
    },
    {
      name: 'providerId',
      label: 'provider ID',
      type: 'autocomplete',
      placeholder: 'provider ID',
      options: referenceOptions.providers ?? [],
    },
    {
      name: 'facilityId',
      label: 'facility ID',
      type: 'autocomplete',
      placeholder: 'facility ID',
      options: referenceOptions.facilities ?? [],
    },
    {
      name: 'generatedBy',
      label: 'generated By',
      type: 'text',
      placeholder: 'generated By',
    },
    {
      name: 'generatedAt',
      label: 'generated At',
      type: 'date',
      date: {
        showButtonBar: true,
      },
    },
    {
      name: 'exportFormat',
      label: 'export Format',
      type: 'text',
      placeholder: 'export Format',
    },
    {
      name: 'active',
      label: 'active',
      type: 'switch',
    },
    ],
  }
}


export function optionalText(value: string) {
  const trimmedValue = value.trim()
  return trimmedValue ? trimmedValue : undefined
}

export function optionalNumber(value: number | null) {
  return typeof value === 'number' ? value : undefined
}

export function optionalDate(value: Date | null) {
  return value ?? undefined
}

export function toFormDate(value?: string | Date | null) {
  if (!value) {
    return null
  }

  const dateValue = value instanceof Date ? value : new Date(value)
  return Number.isNaN(dateValue.getTime()) ? null : dateValue
}

export function formatDate(value?: string | Date | null) {
  if (!value) {
    return '-'
  }

  return new Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: '2-digit',
    year: 'numeric',
  }).format(new Date(value))
}

export function formatBoolean(value?: boolean) {
  return value ? 'Yes' : 'No'
}

export function formatNumber(value?: number | null) {
  return typeof value === 'number' ? String(value) : '-'
}

export function parseStringList(value: string) {
  const values = value
    .split(/[\n,]+/)
    .map((item) => item.trim())
    .filter(Boolean)

  return values.length ? values : undefined
}

export function formatStringList(value: string[] = []) {
  return value.join('\n')
}

export function formatMixed(value: unknown) {
  if (value === undefined || value === null || value === '') {
    return '-'
  }

  if (typeof value === 'string') {
    return value
  }

  try {
    return JSON.stringify(value)
  } catch {
    return String(value)
  }
}

export function mapReportToFormValues(item: Report): ReportFormValues {
  return {
    _id: item._id,
    reportName: item.reportName ?? '',
    reportType: item.reportType ?? '',
    dateFrom: toFormDate(item.dateFrom),
    dateTo: toFormDate(item.dateTo),
    payerId: item.payerId ?? '',
    providerId: item.providerId ?? '',
    facilityId: item.facilityId ?? '',
    generatedBy: item.generatedBy ?? '',
    generatedAt: toFormDate(item.generatedAt),
    exportFormat: item.exportFormat ?? '',
    active: item.active,
  }
}

export function mapReportFormToPayload(values: ReportFormValues): ReportCreatePayload {
  return {
    reportName: optionalText(values.reportName),
    reportType: optionalText(values.reportType),
    dateFrom: optionalDate(values.dateFrom),
    dateTo: optionalDate(values.dateTo),
    payerId: optionalText(values.payerId),
    providerId: optionalText(values.providerId),
    facilityId: optionalText(values.facilityId),
    generatedBy: optionalText(values.generatedBy),
    generatedAt: optionalDate(values.generatedAt),
    exportFormat: optionalText(values.exportFormat),
    active: values.active,
  }
}

function getReportLabel(item: Report, referenceOptions: RcmReferenceOptions = {}) {
  void referenceOptions
  return [item.reportName, item.reportType, formatDate(item.generatedAt)].filter((value) => value && value !== '-').join(' / ') || item._id
}

export function createReportTableColumns(referenceOptions: RcmReferenceOptions = {}): Array<CrudTableColumn<Report>> {
  return [
    {
      key: 'record',
      header: 'Report',
      sortField: 'reportName',
      exportValue: (item) => getReportLabel(item, referenceOptions),
      render: (item) => getReportLabel(item, referenceOptions),
    },
    {
      key: 'payerId',
      header: 'Payer',
      filterable: true,
      sortable: false,
      exportValue: (item) => formatReferenceLabel(referenceOptions.payers, item.payerId),
      render: (item) => formatReferenceLabel(referenceOptions.payers, item.payerId),
    },
    {
      key: 'updatedAt',
      header: 'Updated',
      sortField: 'updated',
      field: 'updatedAt',
      exportValue: (item) => formatDate(item.updatedAt),
      filter: {
        key: 'updatedAt',
        input: 'date',
        placeholder: 'Updated date',
      },
      render: (item) => formatDate(item.updatedAt),
    },
  ]
}

function renderSection(items: Array<[string, string]>) {
  return (
    <dl className="overflow-hidden rounded-lg border border-[var(--color-border)]">
      {items.map(([label, value]) => (
        <div
          key={label}
          className="grid gap-1 border-b border-[var(--color-border)] px-4 py-3 last:border-b-0 sm:grid-cols-[10rem_1fr] sm:items-center"
        >
          <dt className="text-xs font-semibold uppercase tracking-normal text-[var(--color-text-muted)]">
            {label}
          </dt>
          <dd className="whitespace-pre-line break-words text-sm font-semibold text-[var(--color-text-strong)] sm:text-right">
            {value || '-'}
          </dd>
        </div>
      ))}
    </dl>
  )
}

export function renderReportDetails(item: Report, referenceOptions: RcmReferenceOptions = {}) {
  void referenceOptions
  return (
    <div className="space-y-5">
      <section className="space-y-3">
        <h3 className="text-lg font-semibold text-[var(--color-text-strong)]">Report</h3>
        {renderSection([
          ['report ID', item.reportId],
          ['report Name', item.reportName ?? '-'],
          ['report Type', item.reportType ?? '-'],
          ['date From', formatDate(item.dateFrom)],
          ['date To', formatDate(item.dateTo)],
          ['payer ID', formatReferenceLabel(referenceOptions.payers, item.payerId)],
          ['provider ID', formatReferenceLabel(referenceOptions.providers, item.providerId)],
          ['facility ID', formatReferenceLabel(referenceOptions.facilities, item.facilityId)],
          ['generated By', item.generatedBy ?? '-'],
          ['generated At', formatDate(item.generatedAt)],
          ['export Format', item.exportFormat ?? '-'],
          ['active', formatBoolean(item.active)],
        ])}
      </section>
    </div>
  )
}

export function renderReportGridItem(item: Report, referenceOptions: RcmReferenceOptions = {}) {
  void referenceOptions
  return (
    <div className="space-y-3">
      <p className="text-sm font-semibold text-[var(--color-text-strong)]">{getReportLabel(item, referenceOptions)}</p>
      <dl className="space-y-2">
        <div className="space-y-1">
          <dt className="text-[10px] font-semibold uppercase tracking-normal text-[var(--color-text-muted)]">report Type</dt>
          <dd className="text-[13px] font-medium text-[var(--color-text-strong)]">{item.reportType ?? '-'}</dd>
        </div>
      </dl>
    </div>
  )
}
