# Generated by Django 6.0.4 on 2026-04-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationhistory',
            name='image_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationhistory',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
