# Generated by Django 6.0.4 on 2026-05-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_generationhistory_image_prompt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationhistory',
            name='image_prompt',
        ),
        migrations.RemoveField(
            model_name='generationhistory',
            name='image_url',
        ),
        migrations.AddField(
            model_name='generationhistory',
            name='media_urls',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationhistory',
            name='platform_specific_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
