import { Router } from 'express';
import patientRoutes from '../../modules/rcm/patient/patient.route';
import insurancePolicyRoutes from '../../modules/rcm/insurance-policy/insurance-policy.route';
import eligibilityVerificationRoutes from '../../modules/rcm/eligibility-verification/eligibility-verification.route';
import appointmentRoutes from '../../modules/rcm/appointment/appointment.route';
import referralRoutes from '../../modules/rcm/referral/referral.route';
import priorAuthorizationRoutes from '../../modules/rcm/prior-authorization/prior-authorization.route';
import providerRoutes from '../../modules/rcm/provider/provider.route';
import facilityRoutes from '../../modules/rcm/facility/facility.route';
import payerRoutes from '../../modules/rcm/payer/payer.route';
import encounterRoutes from '../../modules/rcm/encounter/encounter.route';
import chargeMasterRoutes from '../../modules/rcm/charge-master/charge-master.route';
import chargeRoutes from '../../modules/rcm/charge/charge.route';
import codingReviewRoutes from '../../modules/rcm/coding-review/coding-review.route';
import claimRoutes from '../../modules/rcm/claim/claim.route';
import claimAiReviewRoutes from '../../modules/rcm/claim-ai-review/claim-ai-review.route';
import claimSubmissionRoutes from '../../modules/rcm/claim-submission/claim-submission.route';
import claimTrackingRoutes from '../../modules/rcm/claim-tracking/claim-tracking.route';
import paymentPostingRoutes from '../../modules/rcm/payment-posting/payment-posting.route';
import eraEobProcessingRoutes from '../../modules/rcm/era-eob-processing/era-eob-processing.route';
import ai835PayloadRoutes from '../../modules/rcm/era-eob-processing/ai-835-payload.route';
import eraExceptionRoutes from '../../modules/rcm/era-exception/era-exception.route';
import adjustmentRoutes from '../../modules/rcm/adjustment/adjustment.route';
import arWorkItemRoutes from '../../modules/rcm/ar-work-item/ar-work-item.route';
import denialRoutes from '../../modules/rcm/denial/denial.route';
import appealRoutes from '../../modules/rcm/appeal/appeal.route';
import correctedClaimRoutes from '../../modules/rcm/corrected-claim/corrected-claim.route';
import patientBillingRoutes from '../../modules/rcm/patient-billing/patient-billing.route';
import patientPaymentRoutes from '../../modules/rcm/patient-payment/patient-payment.route';
import refundRoutes from '../../modules/rcm/refund/refund.route';
import collectionRoutes from '../../modules/rcm/collection/collection.route';
import documentRoutes from '../../modules/rcm/document/document.route';
import taskRoutes from '../../modules/rcm/task/task.route';
import auditLogRoutes from '../../modules/rcm/audit-log/audit-log.route';
import reportRoutes from '../../modules/rcm/report/report.route';
import feeScheduleRoutes from '../../modules/rcm/fee-schedule/fee-schedule.route';
import claimPredictionRoutes from '../../modules/rcm/claim-prediction/claim-prediction.route';
import procedureCodeRoutes from '../../modules/rcm/procedure-code/procedure-code.route';
import ruleRoutes from '../../modules/rcm/rule/rule.route';
import coverageRuleRoutes from '../../modules/rcm/coverage-rule/coverage-rule.route';
import commandCenterRoutes from '../../modules/rcm/command-center/command-center.route';
import timelyFilingAlertRoutes from '../../modules/rcm/timely-filing-alert/timely-filing-alert.route';
import documentationComplianceAlertRoutes from '../../modules/rcm/documentation-compliance-alert/documentation-compliance-alert.route';
import clearinghouseWebhookRoutes from '../../modules/rcm/clearinghouse-webhook/clearinghouse-webhook.route';
import rcmOpsRoutes from '../../modules/rcm/ops/rcm-ops.route';
import rcmEventStreamRoutes from '../../modules/rcm/events/rcm-event-stream.route';

const router = Router();

router.use('/patients', patientRoutes);
router.use('/insurance-policies', insurancePolicyRoutes);
router.use('/eligibility-verifications', eligibilityVerificationRoutes);
router.use('/appointments', appointmentRoutes);
router.use('/referrals', referralRoutes);
router.use('/prior-authorizations', priorAuthorizationRoutes);
router.use('/providers', providerRoutes);
router.use('/facilities', facilityRoutes);
router.use('/payers', payerRoutes);
router.use('/encounters', encounterRoutes);
router.use('/charge-masters', chargeMasterRoutes);
router.use('/charges', chargeRoutes);
router.use('/coding-reviews', codingReviewRoutes);
router.use('/claims', claimRoutes);
router.use('/claim-ai-reviews', claimAiReviewRoutes);
router.use('/claim-submissions', claimSubmissionRoutes);
router.use('/claim-trackings', claimTrackingRoutes);
router.use('/payment-postings', paymentPostingRoutes);
router.use('/era-eob-processings', eraEobProcessingRoutes);
router.use('/ai-835-payloads', ai835PayloadRoutes);
router.use('/era-exceptions', eraExceptionRoutes);
router.use('/adjustments', adjustmentRoutes);
router.use('/ar-work-items', arWorkItemRoutes);
router.use('/denials', denialRoutes);
router.use('/appeals', appealRoutes);
router.use('/corrected-claims', correctedClaimRoutes);
router.use('/patient-billings', patientBillingRoutes);
router.use('/patient-payments', patientPaymentRoutes);
router.use('/refunds', refundRoutes);
router.use('/collections', collectionRoutes);
router.use('/documents', documentRoutes);
router.use('/tasks', taskRoutes);
router.use('/audit-logs', auditLogRoutes);
router.use('/reports', reportRoutes);
router.use('/fee-schedules', feeScheduleRoutes);
router.use('/claim-predictions', claimPredictionRoutes);
router.use('/procedure-codes', procedureCodeRoutes);
router.use('/rules', ruleRoutes);
router.use('/coverage-rules', coverageRuleRoutes);
router.use('/command-center', commandCenterRoutes);
router.use('/timely-filing-alerts', timelyFilingAlertRoutes);
router.use('/documentation-compliance-alerts', documentationComplianceAlertRoutes);
router.use('/clearinghouse-webhooks', clearinghouseWebhookRoutes);
router.use('/ops', rcmOpsRoutes);
router.use('/events', rcmEventStreamRoutes);

export default router;
