import { Router } from 'express';
import authRoutes from '../modules/auth/auth.route';
import userRoutes from '../modules/user/user.route';
import roleRoutes from '../modules/role/role.route';
import menuRoutes from '../modules/menu/menu.route';
import settingsRoutes from '../modules/settings/settings.route';
import tokenRoutes from '../modules/token/token.route';
import dashboardRoutes from '../modules/dashboard/dashboard.route';
import activityRoutes from '../modules/activity/activity.route';
import tableViewRoutes from '../modules/tableView/tableView.route';
import uploadRoutes from '../modules/upload/upload.route';
import bookingRoutes from '../modules/booking/booking.route';
import sevaRoutes, { sevaBookingRouter } from '../modules/seva/seva.route';
import darshanRoutes, { darshanBookingRouter } from '../modules/darshan/darshan.route';
import { accommodationRoomTypeRoutes, accommodationBookingRoutes } from '../modules/accommodation/accommodation.route';
import { prasadamItemRoutes, prasadamOrderRoutes } from '../modules/prasadam/prasadam.route';
import donationFundRoutes from '../modules/donation/donationFund.route';
import donationRoutes from '../modules/donation/donation.route';
import facilityRoutes from '../modules/facility/facility.route';
import announcementRoutes from '../modules/announcement/announcement.route';
import templeProfileRoutes from '../modules/templeProfile/templeProfile.route';
import donorRoutes from '../modules/donor/donor.route';
import propertyRoutes from '../modules/property/property.route';
import assetRoutes from '../modules/asset/asset.route';
import liabilityRoutes from '../modules/liability/liability.route';
import expenseEventRoutes from '../modules/expenseEvent/expenseEvent.route';
import expenseEntryRoutes from '../modules/expenseEntry/expenseEntry.route';
import languageRoutes from '../modules/language/language.route';
import translationRoutes from '../modules/translation/translation.route';
import pageContentRoutes from '../modules/pageContent/pageContent.route';
import templeEventRoutes, { eventRegistrationRouter } from '../modules/templeEvent/templeEvent.route';
import nearbyPlaceRoutes from '../modules/nearbyPlace/nearbyPlace.route';
import templeReconfigureRoutes from '../modules/templeReconfigure/templeReconfigure.route';
import analyticsEventRoutes from '../modules/analytics/analyticsEvent.route';
import navTabRoutes from '../modules/navTab/navTab.route';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/menus', menuRoutes);
router.use('/settings', settingsRoutes);
router.use('/tokens', tokenRoutes);
router.use('/dashboards', dashboardRoutes);
router.use('/activities', activityRoutes);
router.use('/tableViews', tableViewRoutes);
router.use('/upload', uploadRoutes);
router.use('/bookings', bookingRoutes);
router.use('/sevas', sevaRoutes);
router.use('/seva-bookings', sevaBookingRouter);
router.use('/darshan-quotas', darshanRoutes);
router.use('/darshan-bookings', darshanBookingRouter);
router.use('/accommodation-room-types', accommodationRoomTypeRoutes);
router.use('/accommodation-bookings', accommodationBookingRoutes);
router.use('/prasadam-items', prasadamItemRoutes);
router.use('/prasadam-orders', prasadamOrderRoutes);
router.use('/donation-funds', donationFundRoutes);
router.use('/donations', donationRoutes);
router.use('/facilities', facilityRoutes);
router.use('/announcements', announcementRoutes);
router.use('/temple-profile', templeProfileRoutes);
router.use('/donors', donorRoutes);
router.use('/properties', propertyRoutes);
router.use('/assets', assetRoutes);
router.use('/liabilities', liabilityRoutes);
router.use('/expense-events', expenseEventRoutes);
router.use('/expense-entries', expenseEntryRoutes);
router.use('/languages', languageRoutes);
router.use('/translations', translationRoutes);
router.use('/page-content', pageContentRoutes);
router.use('/temple-events', templeEventRoutes);
router.use('/event-registrations', eventRegistrationRouter);
router.use('/nearby-places', nearbyPlaceRoutes);
router.use('/temple-reconfigure', templeReconfigureRoutes);
router.use('/analytics', analyticsEventRoutes);
router.use('/nav-tabs', navTabRoutes);

export default router;
