import { type ChangeEvent, useEffect, useMemo, useRef, useState } from 'react'
import { Check, Copy, FileWarning, ListTodo, Lock, Navigation, ReceiptText, RefreshCw, Unlock, Upload } from 'lucide-react'
import { useLocation, useNavigate, useSearchParams } from 'react-router-dom'
import { Button } from 'primereact/button'
import { Dialog } from 'primereact/dialog'
import { InputText } from 'primereact/inputtext'
import { InputTextarea } from 'primereact/inputtextarea'
import { CrudPage } from '@/components/crud/CrudPage'
import type { CrudPageConfig, CrudTableAction } from '@/types/crud'
import { RcmClaimLifecycleTimeline } from '@/components/rcm/RcmClaimLifecycleTimeline'
import { RcmOpsStatusPanel } from '@/components/rcm/RcmOpsStatusPanel'
import { WorkflowProgressTracker } from '@/components/rcm/WorkflowProgressTracker'
import { WorkflowReturnButton } from '@/components/rcm/WorkflowReturnButton'
import { createEraEobProcessingFormConfig, createEraEobProcessingTableColumns, mapEraEobProcessingFormToPayload, mapEraEobProcessingToFormValues, renderEraEobProcessingDetails, renderEraEobProcessingGridItem } from '@/models/eraEobProcessingModel'
import { useGetEraEobProcessingsQuery, useImport835EraMutation, useLockEraEobProcessingMutation, useUnlockEraEobProcessingMutation } from '@/services/api/endpoints/eraEobProcessingsApi'
import { useGetAi835ByClaimSubmissionQuery, useGenerateAi835PayloadMutation } from '@/services/api/endpoints/ai835PayloadApi'
import { useGetClaimsQuery } from '@/services/api/endpoints/claimsApi'
import { useGetPayersQuery } from '@/services/api/endpoints/payersApi'
import { useGetPaymentPostingsQuery } from '@/services/api/endpoints/paymentPostingsApi'
import type { EntityId } from '@/types/common'
import type { RcmReferenceOptions } from '@/models/rcmReferenceOptions'
import type { EraEobProcessing, EraEobProcessingCreatePayload, EraEobProcessingFormValues, EraEobProcessingUpdatePayload } from '@/types/eraEobProcessing'
import { useToast } from '@/hooks/useToast'
import { getApiErrorMessage } from '@/services/api/apiError'
import { buildWorkflowCriteria, buildWorkflowSearch, mergeWorkflowContext, readWorkflowContext } from '@/utils/rcmWorkflow'

type BulkDeletePayload = {
  ids: EntityId[]
}

const lookupQuery = {
  page: 1,
  limit: 100,
  sortfield: 'updated',
  direction: 'desc' as const,
  criteria: [],
}

function firstMatchedClaimId(item: EraEobProcessing) {
  const firstMatched = item.matchedClaims?.find((claim) => typeof claim.claimId === 'string')
  return typeof firstMatched?.claimId === 'string' ? firstMatched.claimId : undefined
}

export function EraEobProcessingsPage() {
  const { showToast } = useToast()
  const navigate = useNavigate()
  const location = useLocation()
  const [searchParams] = useSearchParams()
  const workflowContext = useMemo(() => readWorkflowContext(searchParams), [searchParams])
  const workflowKey = searchParams.toString()
  const [isImportDialogOpen, setIsImportDialogOpen] = useState(false)
  const [raw835Text, setRaw835Text] = useState('')
  const [importPayerId, setImportPayerId] = useState('')
  const [importPayerName, setImportPayerName] = useState('')
  const [importFileName, setImportFileName] = useState('')
  const [unlockTarget, setUnlockTarget] = useState<EraEobProcessing | null>(null)
  const [unlockReason, setUnlockReason] = useState('')
  const [import835Era, import835State] = useImport835EraMutation()
  const [lockEraEobProcessing, lockState] = useLockEraEobProcessingMutation()
  const [unlockEraEobProcessing, unlockState] = useUnlockEraEobProcessingMutation()
  const claimsQuery = useGetClaimsQuery(lookupQuery)
  const payersQuery = useGetPayersQuery(lookupQuery)
  const paymentPostingsQuery = useGetPaymentPostingsQuery(lookupQuery)
  const returnTo = `${location.pathname}${location.search}`

  const [generateAi835Payload, { isLoading: isGenerating }] = useGenerateAi835PayloadMutation()

  // Load stored payloads from the dedicated ai835payloads collection
  const ai835Query = useGetAi835ByClaimSubmissionQuery(
    workflowContext.claimSubmissionId ?? '',
    { skip: !workflowContext.claimSubmissionId }
  )

  // Track whether we have already auto-triggered a first-time generation
  const autoGeneratedRef = useRef(false)

  // Auto-generate on first open if nothing is stored in DB yet
  useEffect(() => {
    if (
      !autoGeneratedRef.current &&
      workflowContext.claimId &&
      workflowContext.claimSubmissionId &&
      !ai835Query.isLoading &&
      !ai835Query.isFetching &&
      ai835Query.data === null
    ) {
      autoGeneratedRef.current = true
      void generateAi835Payload({
        claimId: workflowContext.claimId,
        claimSubmissionId: workflowContext.claimSubmissionId,
        eraEobProcessingId: workflowContext.eraEobProcessingId,
      })
    }
  }, [
    workflowContext.claimId,
    workflowContext.claimSubmissionId,
    workflowContext.eraEobProcessingId,
    ai835Query.isLoading,
    ai835Query.isFetching,
    ai835Query.data,
    generateAi835Payload,
  ])

  async function handleRegenerate() {
    if (!workflowContext.claimId || !workflowContext.claimSubmissionId) return
    await generateAi835Payload({
      claimId: workflowContext.claimId,
      claimSubmissionId: workflowContext.claimSubmissionId,
      eraEobProcessingId: workflowContext.eraEobProcessingId,
    })
  }

  const helpChildren = useMemo(() => {
    if (!workflowContext.claimSubmissionId) {
      return null
    }

    const isLoading = ai835Query.isLoading || ai835Query.isFetching
    const storedData = ai835Query.data
    const hasError = ai835Query.isError

    const headerRow = (
      <div className="flex items-center justify-between">
        <div>
          <strong>Generated 835 Remittances:</strong>{' '}
          <span className="text-[var(--color-text-muted)]">Copy a scenario and paste into the <strong>Import 835</strong> text area.</span>
        </div>
        <Button
          type="button"
          icon={<RefreshCw className={`h-3.5 w-3.5${isGenerating ? ' animate-spin' : ''}`} />}
          label="Regenerate"
          severity="secondary"
          text
          size="small"
          className="flex items-center gap-1 h-7 px-2 text-xs font-semibold shrink-0"
          loading={isGenerating}
          disabled={isGenerating || isLoading}
          onClick={() => void handleRegenerate()}
        />
      </div>
    )

    if (isLoading || (isGenerating && !storedData)) {
      return (
        <div className="space-y-2 my-3">
          {headerRow}
          <div className="rounded-lg border border-[var(--color-border)] bg-[var(--color-surface-muted)] p-4 flex items-center justify-center gap-2 text-sm text-[var(--color-text-muted)]">
            <RefreshCw className="h-4 w-4 animate-spin text-[var(--color-primary)]" />
            <span>Generating 835 test scenarios from this claim submission...</span>
          </div>
        </div>
      )
    }

    if (hasError) {
      return (
        <div className="space-y-2 my-3">
          {headerRow}
          <div className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">
            Failed to load generated 835 payloads. Please check your backend connection.
          </div>
        </div>
      )
    }

    if (!storedData) {
      return null
    }

    const generatedAt = new Date(storedData.generatedAt).toLocaleString()

    return (
      <div className="space-y-4 my-3">
        <div className="rounded-lg border border-[var(--color-border)] bg-[var(--color-surface-muted)] p-3 text-xs leading-5 text-[var(--color-text-muted)]">
          {headerRow}
          <p className="mt-1 text-[10px] text-[var(--color-text-muted)]">Generated: {generatedAt}</p>
        </div>

        {([
          { key: 'fullPayment835', title: 'Full Payment 835 Import' },
          { key: 'denialPayment835', title: 'Denied 835 Import' },
          { key: 'denialCorrection835', title: 'Reprocessed 835 Import' },
        ] as const).map(({ key, title }) => (
          <div key={key} className="rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] p-3 space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-sm font-semibold text-[var(--color-text-strong)]">{title}</span>
              <CopyButton text={storedData[key]} />
            </div>
            <textarea
              readOnly
              value={storedData[key]}
              rows={3}
              className="w-full rounded-md border border-[var(--color-border)] bg-[var(--color-surface-muted)] p-2 font-mono text-[10px] leading-4 text-[var(--color-text-strong)] focus:outline-none resize-y"
            />
          </div>
        ))}
      </div>
    )
  }, [
    workflowContext.claimSubmissionId,
    ai835Query.isLoading,
    ai835Query.isFetching,
    ai835Query.isError,
    ai835Query.data,
    isGenerating,
    handleRegenerate,
  ])

  const payersOptions = useMemo(
    () =>
      (payersQuery.data?.data ?? []).map((item) => ({
        label: item.payerName ? `${item.payerName} (${item.payerId ?? item._id})` : item.payerId ?? item._id,
        value: item.payerId ?? item._id,
      })),
    [payersQuery.data],
  )
  const paymentPostingsOptions = useMemo(
    () =>
      (paymentPostingsQuery.data?.data ?? []).map((item) => ({
        label: [item.paymentDate, item.checkNumber, item.postingStatus].filter(Boolean).join(' ') || item._id,
        value: item._id,
      })),
    [paymentPostingsQuery.data],
  )

  const referenceOptions: RcmReferenceOptions = useMemo(
    () => ({
      payers: payersOptions,
      paymentPostings: paymentPostingsOptions,
    }),
    [payersOptions, paymentPostingsOptions],
  )
  const claimById = useMemo(() => {
    const nextClaimById = new Map<string, { closureStatus?: string; paymentStatus?: string; claimStatus?: string }>()

    for (const claim of claimsQuery.data?.data ?? []) {
      nextClaimById.set(claim._id, claim)
    }

    return nextClaimById
  }, [claimsQuery.data])

  const crudConfig: CrudPageConfig<
    EraEobProcessing,
    EraEobProcessingFormValues,
    EraEobProcessingCreatePayload,
    EraEobProcessingUpdatePayload,
    BulkDeletePayload
  > = useMemo(
    () => ({
      title: 'ERA / EOB Processing',
      resourceName: 'ERA / EOB Processing',
      help: {
        title: 'ERA / EOB Processing',
        intro: 'Import the payer 835 ERA/EOB after an accepted claim submission, and follow the next action workflow: view AR, then view claim for a full closed claim, or view denial for resolving denials, and view payment for patient billing and refunds.',
        steps: [
          {
            label: 'Import 835',
            icon: <Upload className="h-4 w-4" aria-hidden="true" />,
            description: 'Click Import 835, select the payer, paste or auto-fill the ERA payload, and submit the import.',
          },
          {
            label: 'View AR',
            icon: <ListTodo className="h-4 w-4" aria-hidden="true" />,
            description: 'Navigate to AR follow-up to trace outstanding balances and determine the next workflow step.',
          },
          {
            label: 'View Claim',
            icon: <Navigation className="h-4 w-4" aria-hidden="true" />,
            description: 'View the claim details screen to review and verify information for fully closed claims.',
          },
          {
            label: 'View Denial',
            icon: <FileWarning className="h-4 w-4" aria-hidden="true" />,
            description: 'Access denial records to inspect unpaid adjustment reason codes and take action to resolve denials.',
          },
          {
            label: 'View Payment',
            icon: <ReceiptText className="h-4 w-4" aria-hidden="true" />,
            description: 'Inspect posted payments to manage patient billing and process refunds.',
          },
        ],
      },
      helpChildren,
      showCreateButton: false,
      createButtonLabel: 'Add ERA / EOB Processing',
      createDialogTitle: 'Add era / eob processing',
      editDialogTitle: 'Edit era / eob processing',
      viewDialogTitle: 'ERA / EOB Processing details',
      deleteDialogTitle: 'Delete era / eob processing?',
      emptyMessage: 'No era / eob processings found.',
      exportFileName: 'era-eob-processings',
      pageSizeOptions: [10, 20, 50],
      defaultQuery: {
        page: 1,
        limit: 20,
        sortfield: 'updated',
        direction: 'desc',
        criteria: buildWorkflowCriteria('eraEobProcessing', workflowContext),
        dashboardQueue: workflowContext.dashboardQueue,
        dashboardEntityId: workflowContext.dashboardEntityId,
      },
      permissions: {
        module: 'era-eob-processings',
      },
      getRowId: (item) => item._id,
      getRowLabel: (item) => renderEraEobProcessingGridItem(item, referenceOptions) ? String(item._id) : String(item._id),
      table: {
        columns: createEraEobProcessingTableColumns(referenceOptions),
      },
      form: createEraEobProcessingFormConfig(referenceOptions),
      api: {
        useListQuery: useGetEraEobProcessingsQuery,
      },
      mapItemToFormValues: mapEraEobProcessingToFormValues,
      mapFormValuesToCreatePayload: mapEraEobProcessingFormToPayload,
      mapFormValuesToUpdatePayload: (values) => mapEraEobProcessingFormToPayload(values),
      deleteDialogMessage: (item) => `This will permanently delete ${item._id}.`,
      slots: {
        beforeContent: () => (
          <div className="space-y-3">
            <RcmOpsStatusPanel />
            <WorkflowReturnButton context={workflowContext} />
            <WorkflowProgressTracker currentStage="eraEobProcessing" context={workflowContext} />
          </div>
        ),
        toolbarRight: () => (
          <Button
            type="button"
            label="Import 835"
            icon={<Upload className="h-3.5 w-3.5" />}
            severity="secondary"
            outlined
            className="flex h-8 items-center gap-1 px-3 text-xs font-semibold"
            onClick={() => setIsImportDialogOpen(true)}
          />
        ),
        rowActions: (item, defaultActions) => {
          const claimId = firstMatchedClaimId(item)
          const rowContext = mergeWorkflowContext(workflowContext, {
            claimId,
            eraEobProcessingId: item._id,
            paymentPostingId: item.paymentId,
            returnTo,
            returnLabel: 'Back to ERA / EOB',
          })
          const actions: Array<CrudTableAction<EraEobProcessing>> = []

          if (claimId) {
            actions.push({
              label: 'View Claim',
              icon: <Navigation className="h-4 w-4" />,
              onClick: () => navigate(`/rcm/claims${buildWorkflowSearch(rowContext)}`),
            })
          }

          actions.push(
            {
              label: 'View Payment',
              icon: <ReceiptText className="h-4 w-4" />,
              disabled: !item.paymentId,
              onClick: () => navigate(`/rcm/payment-postings${buildWorkflowSearch(rowContext)}`),
            },
            {
              label: 'View Denial',
              icon: <FileWarning className="h-4 w-4" />,
              onClick: () => navigate(`/rcm/denials${buildWorkflowSearch(rowContext)}`),
            },
            {
              label: 'View AR',
              icon: <ListTodo className="h-4 w-4" />,
              onClick: () => navigate(`/rcm/ar-work-items${buildWorkflowSearch(rowContext)}`),
            },
          )

          return [...actions, ...defaultActions.filter((action) => typeof action.label === 'string' && action.label.startsWith('View '))]
        },
        viewContent: (item) => {
          const claimId = firstMatchedClaimId(item)
          const claim = claimId ? claimById.get(claimId) : undefined
          const claimClosureStatus = claim?.closureStatus ?? (claimId === workflowContext.claimId ? workflowContext.closureStatus : undefined)

          return (
          <div className="space-y-4">
            <RcmClaimLifecycleTimeline
              currentStage="eraEobProcessing"
              claimLabel={claimId}
              context={mergeWorkflowContext(workflowContext, {
                claimId,
                eraEobProcessingId: item._id,
                paymentPostingId: item.paymentId,
                paymentStatus: claim?.paymentStatus,
                closureStatus: claimClosureStatus,
                returnTo,
                returnLabel: 'Back to ERA / EOB',
              })}
              statuses={{
                claim: claim?.claimStatus,
                claimTracking: 'ACCEPTED',
                waitingForERA: 'ERA_RECEIVED',
                eraEobProcessing: item.reconciliationStatus,
                paymentPosting: item.paymentId ? 'POSTED' : undefined,
                denial: item.importErrors?.length ? 'NEEDS_REVIEW' : undefined,
                arWorkItem: item.unmatchedAmount && item.unmatchedAmount > 0 ? 'OPEN' : undefined,
                closed: claimClosureStatus === 'CLOSED' ? 'CLOSED' : undefined,
              }}
              nextAction={
                claimClosureStatus === 'CLOSED'
                  ? 'Claim is closed. Review audit trail if additional financial activity appears.'
                  : item.reconciliationStatus === 'RECONCILED'
                  ? item.accountingLocked ? 'Accounting is locked. Monitor downstream patient balance or close the claim.' : 'Lock accounting after reconciliation review.'
                  : 'Resolve ERA exceptions, unmatched claims, or payment variances.'
              }
            />
            <div className="flex flex-wrap items-center justify-end gap-2">
              {!item.accountingLocked && item.reconciliationStatus === 'RECONCILED' ? (
                <Button
                  type="button"
                  label="Lock Accounting"
                  icon={<Lock className="h-3.5 w-3.5" />}
                  severity="success"
                  outlined
                  loading={lockState.isLoading}
                  onClick={() => void handleLockAccounting(item)}
                />
              ) : null}
              {item.accountingLocked ? (
                <Button
                  type="button"
                  label="Admin Unlock"
                  icon={<Unlock className="h-3.5 w-3.5" />}
                  severity="warning"
                  outlined
                  loading={unlockState.isLoading}
                  onClick={() => {
                    setUnlockTarget(item)
                    setUnlockReason('')
                  }}
                />
              ) : null}
            </div>
            {renderEraEobProcessingDetails(item, referenceOptions)}
          </div>
          )
        },
        gridItem: (item) => renderEraEobProcessingGridItem(item, referenceOptions),
      },
    }),
    [claimById, lockState.isLoading, navigate, referenceOptions, returnTo, unlockState.isLoading, workflowContext, helpChildren],
  )

  async function handleLockAccounting(item: EraEobProcessing) {
    try {
      await lockEraEobProcessing({
        id: item._id,
        data: { reason: 'Reconciled ERA accounting close' },
      }).unwrap()
      showToast({ severity: 'success', summary: 'Accounting locked', detail: 'The reconciled ERA batch is now locked.' })
    } catch (error) {
      showToast({ severity: 'error', summary: 'Accounting lock failed', detail: getApiErrorMessage(error) })
    }
  }

  async function handleUnlockAccounting() {
    if (!unlockTarget || !unlockReason.trim()) {
      return
    }

    try {
      await unlockEraEobProcessing({
        id: unlockTarget._id,
        data: { reason: unlockReason.trim() },
      }).unwrap()
      showToast({ severity: 'success', summary: 'Accounting unlocked', detail: 'The ERA batch is available for controlled correction.' })
      setUnlockTarget(null)
      setUnlockReason('')
    } catch (error) {
      showToast({ severity: 'error', summary: 'Accounting unlock failed', detail: getApiErrorMessage(error) })
    }
  }

  async function handleImport835() {
    try {
      const result = await import835Era({
        raw835Text,
        payerId: importPayerId.trim() || undefined,
        payerName: importPayerName.trim() || undefined,
        eraFileReference: importFileName.trim() || undefined,
        fileMetadata: importFileName.trim() ? { fileName: importFileName.trim() } : undefined,
      }).unwrap()
      if (result.duplicate) {
        showToast({
          severity: 'warn',
          summary: '835 Import Ignored',
          detail: result.importErrors?.[0] || 'Duplicate ERA trace/check number ignored.',
        })
      } else {
        showToast({
          severity: 'success',
          summary: '835 imported',
          detail: `Matched ${result.matchedClaims.length} claim${result.matchedClaims.length === 1 ? '' : 's'}, unmatched ${result.unmatchedClaims.length}.`,
        })
      }
      setRaw835Text('')
      setImportPayerId('')
      setImportPayerName('')
      setImportFileName('')
      setIsImportDialogOpen(false)
    } catch (error) {
      showToast({ severity: 'error', summary: '835 import failed', detail: getApiErrorMessage(error) })
    }
  }

  async function handle835FileSelection(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]
    event.target.value = ''

    if (!file) {
      return
    }

    try {
      const text = await file.text()
      setRaw835Text(text)
      setImportFileName((current) => current || file.name)
    } catch (error) {
      showToast({ severity: 'error', summary: '835 file read failed', detail: getApiErrorMessage(error) })
    }
  }

  return (
    <>
      <CrudPage key={workflowKey || 'era-eob-processings'} config={crudConfig} />
      <Dialog
        header="Test/Admin: Import 835 ERA"
        visible={isImportDialogOpen}
        onHide={() => setIsImportDialogOpen(false)}
        style={{ width: 'min(960px, 96vw)' }}
        modal
        blockScroll
        draggable={false}
        resizable={false}
        className="crud-view-dialog"
        maskClassName="crud-form-dialog-mask"
      >
        <div className="space-y-4 text-[var(--color-text)]">
          <p className="text-sm text-[var(--color-text-muted)]">
            Paste a test/admin 835 ERA payload to continue the post-submission workflow when clearinghouse webhooks are unavailable.
          </p>
          <div className="grid gap-3 md:grid-cols-3">
            <label className="flex min-w-0 flex-col gap-1.5">
              <span className="text-sm font-semibold leading-5 text-[var(--color-text-strong)]">Payer ID</span>
              <InputText
                value={importPayerId}
                onChange={(event) => setImportPayerId(event.target.value)}
                className="w-full"
                placeholder="Optional payer ID"
              />
            </label>
            <label className="flex min-w-0 flex-col gap-1.5">
              <span className="text-sm font-semibold leading-5 text-[var(--color-text-strong)]">Payer name</span>
              <InputText
                value={importPayerName}
                onChange={(event) => setImportPayerName(event.target.value)}
                className="w-full"
                placeholder="Optional payer name"
              />
            </label>
            <label className="flex min-w-0 flex-col gap-1.5">
              <span className="text-sm font-semibold leading-5 text-[var(--color-text-strong)]">File name/reference</span>
              <InputText
                value={importFileName}
                onChange={(event) => setImportFileName(event.target.value)}
                className="w-full"
                placeholder="Optional file reference"
              />
            </label>
          </div>
          <label className="block space-y-1">
            <span className="text-xs font-semibold uppercase tracking-normal text-[var(--color-text-muted)]">Raw X12 835</span>
            <InputText
              type="file"
              accept=".835,.x12,.txt,text/plain"
              onChange={(event) => void handle835FileSelection(event as ChangeEvent<HTMLInputElement>)}
              className="mb-2 w-full"
            />
            <InputTextarea
              value={raw835Text}
              onChange={(event) => setRaw835Text(event.target.value)}
              rows={14}
              className="w-full font-mono text-xs"
              placeholder="ISA*00*...~GS*HP*...~ST*835..."
              autoResize={false}
            />
            <span className="text-xs leading-5 text-[var(--color-text-muted)]">
              Raw EDI is processed by the backend and stored according to the configured redaction/raw-payload policy.
            </span>
          </label>
          <div className="flex flex-wrap justify-end gap-2 border-t border-[var(--color-border)] pt-4">
            <Button
              type="button"
              label="Cancel"
              severity="secondary"
              outlined
              onClick={() => setIsImportDialogOpen(false)}
            />
            <Button
              type="button"
              label="Import ERA"
              loading={import835State.isLoading}
              disabled={!raw835Text.trim()}
              onClick={() => void handleImport835()}
            />
          </div>
        </div>
      </Dialog>
      <Dialog
        header="Admin accounting unlock"
        visible={Boolean(unlockTarget)}
        onHide={() => {
          setUnlockTarget(null)
          setUnlockReason('')
        }}
        style={{ width: 'min(640px, 96vw)' }}
        modal
        blockScroll
        draggable={false}
        resizable={false}
        className="crud-view-dialog"
        maskClassName="crud-form-dialog-mask"
      >
        <div className="space-y-4 text-[var(--color-text)]">
          <label className="flex min-w-0 flex-col gap-1.5">
            <span className="text-sm font-semibold leading-5 text-[var(--color-text-strong)]">Override reason</span>
            <InputTextarea
              value={unlockReason}
              onChange={(event) => setUnlockReason(event.target.value)}
              rows={4}
              className="w-full"
              placeholder="Required reason for accounting override"
              autoResize={false}
            />
          </label>
          <div className="flex flex-wrap justify-end gap-2 border-t border-[var(--color-border)] pt-4">
            <Button
              type="button"
              label="Cancel"
              severity="secondary"
              outlined
              onClick={() => {
                setUnlockTarget(null)
                setUnlockReason('')
              }}
            />
            <Button
              type="button"
              label="Unlock"
              severity="warning"
              loading={unlockState.isLoading}
              disabled={!unlockReason.trim()}
              onClick={() => void handleUnlockAccounting()}
            />
          </div>
        </div>
      </Dialog>
    </>
  )
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false)

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      const textArea = document.createElement('textarea')
      textArea.value = text
      document.body.appendChild(textArea)
      textArea.select()
      document.execCommand('copy')
      document.body.removeChild(textArea)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  return (
    <Button
      type="button"
      icon={copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
      label={copied ? 'Copied' : 'Copy'}
      severity={copied ? 'success' : 'secondary'}
      text
      size="small"
      className="flex items-center gap-1 h-7 px-2 text-xs font-semibold"
      onClick={handleCopy}
    />
  )
}
