import { z } from 'zod';

export const createClaimTrackingSchema = z.object({
  body: z.object({
    claimId: z.string().trim().min(1, 'Claim is required.'),
    claimSubmissionId: z.string().trim().optional(),
    timestamp: z.coerce.date().optional(),
    source: z.string().trim().optional(),
    trackingSource: z.enum(['REAL', 'SIMULATED']).optional(),
    responseType: z.enum(['SUBMISSION', 'ACK_999', 'ACK_277CA', 'STATUS_UPDATE']).optional(),
    eventType: z.enum([
      'SUBMISSION_CREATED',
      'SUBMISSION_SENT',
      'SUBMISSION_FAILED',
      'ACK_999_ACCEPTED',
      'ACK_999_REJECTED',
      'ACK_277CA_ACCEPTED',
      'ACK_277CA_REJECTED',
      'CLAIM_PENDING',
      'CLAIM_STATUS_UPDATED',
    ]).optional(),
    normalizedStatus: z.enum(['DRAFT', 'READY', 'SUBMITTED', 'PENDING', 'ACCEPTED', 'REJECTED', 'FAILED']).optional(),
    rawStatusCode: z.string().trim().optional(),
    summary: z.string().trim().optional(),
    controlNumber: z.string().trim().optional(),
    externalSubmissionId: z.string().trim().optional(),
    claimControlNumber: z.string().trim().optional(),
    clearinghouseTraceNumber: z.string().trim().optional(),
    payerClaimNumber: z.string().trim().optional(),
    acknowledgementType: z.string().trim().optional(),
    statusCode: z.string().trim().optional(),
    statusDescription: z.string().trim().optional(),
    receivedDate: z.coerce.date().optional(),
    rejectionLevel: z.string().trim().optional(),
    rejectionSource: z.string().trim().optional(),
    rejectionReasonCodes: z.array(z.string().trim()).optional(),
    stcCategoryCode: z.string().trim().optional(),
    stcStatusCode: z.string().trim().optional(),
    stcEntityCode: z.string().trim().optional(),
    affectedServiceLine: z.string().trim().optional(),
    nextActionRequired: z.string().trim().optional(),
    active: z.boolean().optional(),
  }),
});

export const updateClaimTrackingSchema = z.object({
  body: z.object({
    claimId: z.string().trim().min(1, 'Claim is required.').optional(),
    claimSubmissionId: z.string().trim().optional(),
    timestamp: z.coerce.date().optional(),
    source: z.string().trim().optional(),
    trackingSource: z.enum(['REAL', 'SIMULATED']).optional(),
    responseType: z.enum(['SUBMISSION', 'ACK_999', 'ACK_277CA', 'STATUS_UPDATE']).optional(),
    eventType: z.enum([
      'SUBMISSION_CREATED',
      'SUBMISSION_SENT',
      'SUBMISSION_FAILED',
      'ACK_999_ACCEPTED',
      'ACK_999_REJECTED',
      'ACK_277CA_ACCEPTED',
      'ACK_277CA_REJECTED',
      'CLAIM_PENDING',
      'CLAIM_STATUS_UPDATED',
    ]).optional(),
    normalizedStatus: z.enum(['DRAFT', 'READY', 'SUBMITTED', 'PENDING', 'ACCEPTED', 'REJECTED', 'FAILED']).optional(),
    rawStatusCode: z.string().trim().optional(),
    summary: z.string().trim().optional(),
    controlNumber: z.string().trim().optional(),
    externalSubmissionId: z.string().trim().optional(),
    claimControlNumber: z.string().trim().optional(),
    clearinghouseTraceNumber: z.string().trim().optional(),
    payerClaimNumber: z.string().trim().optional(),
    acknowledgementType: z.string().trim().optional(),
    statusCode: z.string().trim().optional(),
    statusDescription: z.string().trim().optional(),
    receivedDate: z.coerce.date().optional(),
    rejectionLevel: z.string().trim().optional(),
    rejectionSource: z.string().trim().optional(),
    rejectionReasonCodes: z.array(z.string().trim()).optional(),
    stcCategoryCode: z.string().trim().optional(),
    stcStatusCode: z.string().trim().optional(),
    stcEntityCode: z.string().trim().optional(),
    affectedServiceLine: z.string().trim().optional(),
    nextActionRequired: z.string().trim().optional(),
    active: z.boolean().optional(),
  }),
  params: z.object({
    id: z.string().min(24),
  }),
});
