import { z } from 'zod';

export const createPriorAuthorizationSchema = z.object({
  body: z.object({
    patientId: z.string().trim().optional(),
    insuranceId: z.string().trim().optional(),
    payerId: z.string().trim().optional(),
    providerId: z.string().trim().optional(),
    facilityId: z.string().trim().optional(),
    serviceDate: z.coerce.date().optional(),
    placeOfService: z.string().trim().optional(),
    procedureCodes: z.array(z.string().trim()).optional(),
    diagnosisCodes: z.array(z.string().trim()).optional(),
    modifiers: z.array(z.string().trim()).optional(),
    authorizationRequired: z.boolean().optional(),
    authorizationType: z.string().trim().optional(),
    requestDate: z.coerce.date().optional(),
    requestedUnits: z.coerce.number().optional(),
    approvedUnits: z.coerce.number().optional(),
    authNumber: z.string().trim().optional(),
    authorizationStatus: z.string().trim().optional(),
    expirationDate: z.coerce.date().optional(),
    denialReason: z.string().trim().optional(),
    notes: z.string().trim().optional(),
    statusHistory: z.array(z.string().trim()).optional(),
    active: z.boolean().optional(),
  }),
});

export const updatePriorAuthorizationSchema = z.object({
  body: z.object({
    patientId: z.string().trim().optional(),
    insuranceId: z.string().trim().optional(),
    payerId: z.string().trim().optional(),
    providerId: z.string().trim().optional(),
    facilityId: z.string().trim().optional(),
    serviceDate: z.coerce.date().optional(),
    placeOfService: z.string().trim().optional(),
    procedureCodes: z.array(z.string().trim()).optional(),
    diagnosisCodes: z.array(z.string().trim()).optional(),
    modifiers: z.array(z.string().trim()).optional(),
    authorizationRequired: z.boolean().optional(),
    authorizationType: z.string().trim().optional(),
    requestDate: z.coerce.date().optional(),
    requestedUnits: z.coerce.number().optional(),
    approvedUnits: z.coerce.number().optional(),
    authNumber: z.string().trim().optional(),
    authorizationStatus: z.string().trim().optional(),
    expirationDate: z.coerce.date().optional(),
    denialReason: z.string().trim().optional(),
    notes: z.string().trim().optional(),
    statusHistory: z.array(z.string().trim()).optional(),
    active: z.boolean().optional(),
  }),
  params: z.object({
    id: z.string().min(24),
  }),
});