import { apiSlice } from '@/services/api/apiSlice'
import { readResponsePath } from '@/services/api/responseTransform'
import type {
  MineCareAction,
  MineCareAlert,
  MineCareBudgetForecast,
  MineCareCalendar,
  MineCareChecklist,
  MineCareBreakdownRecord,
  MineCareCompleteServicePayload,
  MineCareConsumedPart,
  MineCareCopilotResponse,
  MineCareDashboardSummary,
  MineCareDocumentExtractionResponse,
  MineCareDowntimeScenario,
  MineCareEquipment,
  MineCareEquipmentDetails,
  MineCareEquipmentPayload,
  MineCareExecutiveReport,
  MineCareKnowledgeAnswer,
  MineCareKnowledgeDocument,
  MineCareObservation,
  MineCareMaintenanceRecord,
  MineCareProcurementComparison,
  MineCareProcurementOption,
  MineCareRecordBreakdownRepairPayload,
  MineCareRecommendation,
  MineCareRepairReplaceAnalysis,
  MineCareRisk,
  MineCareRootCauseAnalysis,
  MineCareSparePart,
  MineCareTechnician,
  MineCareVendorSla,
  MineCareVendorSlaScorecard,
  MineCareWarrantyClaim,
  MineCareWarrantyStatus,
} from '@/types/mineCareAi'

const endpoint = '/minecare-ai'
const data = <T>(response: unknown) => readResponsePath<T>(response, 'data')

export const mineCareAiApi = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    getMineCareDashboardSummary: builder.query<MineCareDashboardSummary, void>({
      query: () => ({ url: `${endpoint}/dashboard/summary` }),
      transformResponse: data<MineCareDashboardSummary>,
      providesTags: ['MineCareAi'],
    }),
    getMineCareEquipment: builder.query<MineCareEquipment[], Record<string, string | undefined> | void>({
      query: (params) => ({ url: `${endpoint}/equipment`, params }),
      transformResponse: data<MineCareEquipment[]>,
      providesTags: ['MineCareAi'],
    }),
    getMineCareEquipmentDetails: builder.query<MineCareEquipmentDetails, string>({
      query: (id) => ({ url: `${endpoint}/equipment/${id}` }),
      transformResponse: data<MineCareEquipmentDetails>,
      providesTags: ['MineCareAi'],
    }),
    createMineCareEquipment: builder.mutation<MineCareEquipmentDetails, Partial<MineCareEquipmentPayload>>({
      query: (payload) => ({ url: `${endpoint}/equipment`, method: 'POST', data: payload }),
      transformResponse: data<MineCareEquipmentDetails>,
      invalidatesTags: ['MineCareAi'],
    }),
    extractMineCareEquipmentDocuments: builder.mutation<MineCareDocumentExtractionResponse, FormData>({
      query: (payload) => ({
        url: `${endpoint}/equipment/extract-documents`,
        method: 'POST',
        data: payload,
        timeout: 180000,
      }),
      transformResponse: data<MineCareDocumentExtractionResponse>,
    }),
    updateMineCareEquipment: builder.mutation<MineCareEquipmentDetails, { id: string; data: Partial<MineCareEquipmentPayload> }>({
      query: ({ id, data: payload }) => ({ url: `${endpoint}/equipment/${id}`, method: 'PUT', data: payload }),
      transformResponse: data<MineCareEquipmentDetails>,
      invalidatesTags: ['MineCareAi'],
    }),
    deleteMineCareEquipment: builder.mutation<{ id: string }, string>({
      query: (id) => ({ url: `${endpoint}/equipment/${id}`, method: 'DELETE' }),
      transformResponse: data<{ id: string }>,
      invalidatesTags: ['MineCareAi'],
    }),
    getMineCareServiceCalendar: builder.query<MineCareCalendar, void>({
      query: () => ({ url: `${endpoint}/service-calendar` }),
      transformResponse: data<MineCareCalendar>,
      providesTags: ['MineCareAi'],
    }),
    completeMineCareService: builder.mutation<{ maintenanceHistory: MineCareMaintenanceRecord; consumedParts: MineCareConsumedPart[]; equipment: MineCareEquipment }, MineCareCompleteServicePayload>({
      query: (payload) => ({ url: `${endpoint}/service-calendar/complete`, method: 'POST', data: payload }),
      transformResponse: data<{ maintenanceHistory: MineCareMaintenanceRecord; consumedParts: MineCareConsumedPart[]; equipment: MineCareEquipment }>,
      invalidatesTags: ['MineCareAi'],
    }),
    recordMineCareBreakdownRepair: builder.mutation<{ breakdown: MineCareBreakdownRecord; maintenanceHistory: MineCareMaintenanceRecord | null; equipment: MineCareEquipment }, MineCareRecordBreakdownRepairPayload>({
      query: (payload) => ({ url: `${endpoint}/breakdowns/record-repair`, method: 'POST', data: payload }),
      transformResponse: data<{ breakdown: MineCareBreakdownRecord; maintenanceHistory: MineCareMaintenanceRecord | null; equipment: MineCareEquipment }>,
      invalidatesTags: ['MineCareAi'],
    }),
    getMineCareRiskRanking: builder.query<MineCareRisk[], void>({
      query: () => ({ url: `${endpoint}/risk-ranking` }),
      transformResponse: data<MineCareRisk[]>,
      providesTags: ['MineCareAi'],
    }),
    getMineCareWarrantyAlerts: builder.query<MineCareWarrantyStatus[], void>({
      query: () => ({ url: `${endpoint}/warranty-alerts` }),
      transformResponse: data<MineCareWarrantyStatus[]>,
      providesTags: ['MineCareAi'],
    }),
    getMineCareWarrantyClaims: builder.query<MineCareWarrantyClaim[], void>({
      query: () => ({ url: `${endpoint}/warranty-claims` }),
      transformResponse: data<MineCareWarrantyClaim[]>,
      providesTags: ['MineCareAi'],
    }),
    getMineCareObservations: builder.query<MineCareObservation[], void>({
      query: () => ({ url: `${endpoint}/operator-observations` }),
      transformResponse: data<MineCareObservation[]>,
      providesTags: ['MineCareAi'],
    }),
    createMineCareObservation: builder.mutation<MineCareObservation, Partial<MineCareObservation>>({
      query: (payload) => ({ url: `${endpoint}/operator-observations`, method: 'POST', data: payload }),
      transformResponse: data<MineCareObservation>,
      invalidatesTags: ['MineCareAi'],
    }),
    getMineCareAlerts: builder.query<MineCareAlert[], void>({
      query: () => ({ url: `${endpoint}/alerts` }),
      transformResponse: data<MineCareAlert[]>,
      providesTags: ['MineCareAi'],
    }),
    updateMineCareAlertStatus: builder.mutation<MineCareAlert, { id: string; status: 'Open' | 'Acknowledged' | 'Closed' }>({
      query: ({ id, status }) => ({ url: `${endpoint}/alerts/${encodeURIComponent(id)}/status`, method: 'PATCH', data: { status } }),
      transformResponse: data<MineCareAlert>,
      invalidatesTags: ['MineCareAi'],
    }),
    getMineCareSpareParts: builder.query<MineCareSparePart[], void>({
      query: () => ({ url: `${endpoint}/spare-parts` }),
      transformResponse: data<MineCareSparePart[]>,
      providesTags: ['MineCareAi'],
    }),
    getMineCareBudgetForecast: builder.query<MineCareBudgetForecast, void>({
      query: () => ({ url: `${endpoint}/budget-forecast` }),
      transformResponse: data<MineCareBudgetForecast>,
      providesTags: ['MineCareAi'],
    }),
    getMineCareActionCenter: builder.query<MineCareAction[], void>({
      query: () => ({ url: `${endpoint}/action-center` }),
      transformResponse: data<MineCareAction[]>,
      providesTags: ['MineCareAi'],
    }),
    getMineCareRecommendations: builder.query<MineCareRecommendation[], void>({
      query: () => ({ url: `${endpoint}/recommendations` }),
      transformResponse: data<MineCareRecommendation[]>,
      providesTags: ['MineCareAi'],
    }),
    updateMineCareRecommendationStatus: builder.mutation<MineCareRecommendation, { id: string; status: MineCareRecommendation['status'] }>({
      query: ({ id, status }) => ({ url: `${endpoint}/recommendations/${encodeURIComponent(id)}/status`, method: 'PATCH', data: { status } }),
      transformResponse: data<MineCareRecommendation>,
      invalidatesTags: ['MineCareAi'],
    }),
    updateMineCareActionStatus: builder.mutation<MineCareAction, { id: string; status: 'Open' | 'In Progress' | 'Completed' }>({
      query: ({ id, status }) => ({ url: `${endpoint}/action-center/${encodeURIComponent(id)}/status`, method: 'PATCH', data: { status } }),
      transformResponse: data<MineCareAction>,
      invalidatesTags: ['MineCareAi'],
    }),
    askMineCareCopilot: builder.mutation<MineCareCopilotResponse, { question: string }>({
      query: (payload) => ({ url: `${endpoint}/copilot`, method: 'POST', data: payload }),
      transformResponse: data<MineCareCopilotResponse>,
    }),
    generateMineCareExecutiveReport: builder.mutation<MineCareExecutiveReport, { period: 'weekly' | 'monthly' }>({
      query: (payload) => ({ url: `${endpoint}/reports/executive`, method: 'POST', data: payload }),
      transformResponse: data<MineCareExecutiveReport>,
    }),
    updateMineCareWarrantyClaimStatus: builder.mutation<MineCareWarrantyClaim, { id: string; status: 'Potential' | 'Submitted' | 'Approved' | 'Rejected' }>({
      query: ({ id, status }) => ({ url: `${endpoint}/warranty-claims/${encodeURIComponent(id)}/status`, method: 'PATCH', data: { status } }),
      transformResponse: data<MineCareWarrantyClaim>,
      invalidatesTags: ['MineCareAi'],
    }),
    getMineCareRootCauses: builder.query<MineCareRootCauseAnalysis[], void>({
      query: () => ({ url: `${endpoint}/root-cause` }),
      transformResponse: data<MineCareRootCauseAnalysis[]>,
      providesTags: ['MineCareAi'],
    }),
    analyzeMineCareRootCause: builder.mutation<MineCareRootCauseAnalysis, Partial<MineCareRootCauseAnalysis>>({
      query: (payload) => ({ url: `${endpoint}/root-cause/analyze`, method: 'POST', data: payload }),
      transformResponse: data<MineCareRootCauseAnalysis>,
      invalidatesTags: ['MineCareAi'],
    }),
    getMineCareChecklists: builder.query<MineCareChecklist[], void>({
      query: () => ({ url: `${endpoint}/checklists` }),
      transformResponse: data<MineCareChecklist[]>,
      providesTags: ['MineCareAi'],
    }),
    generateMineCareChecklist: builder.mutation<MineCareChecklist, { equipmentId: string; serviceType?: string; requiredParts?: string[] }>({
      query: (payload) => ({ url: `${endpoint}/checklists/generate`, method: 'POST', data: payload }),
      transformResponse: data<MineCareChecklist>,
      invalidatesTags: ['MineCareAi'],
    }),
    updateMineCareChecklistItem: builder.mutation<MineCareChecklist, { id: string; itemId: string; completed: boolean }>({
      query: ({ id, itemId, completed }) => ({ url: `${endpoint}/checklists/${encodeURIComponent(id)}/items/${encodeURIComponent(itemId)}`, method: 'PATCH', data: { completed } }),
      transformResponse: data<MineCareChecklist>,
      invalidatesTags: ['MineCareAi'],
    }),
    uploadMineCareKnowledgeDocument: builder.mutation<MineCareKnowledgeDocument[], FormData>({
      query: (payload) => ({ url: `${endpoint}/knowledge/upload`, method: 'POST', data: payload, timeout: 180000 }),
      transformResponse: data<MineCareKnowledgeDocument[]>,
      invalidatesTags: ['MineCareAi'],
    }),
    getMineCareKnowledgeDocuments: builder.query<MineCareKnowledgeDocument[], void>({
      query: () => ({ url: `${endpoint}/knowledge/documents` }),
      transformResponse: data<MineCareKnowledgeDocument[]>,
      providesTags: ['MineCareAi'],
    }),
    askMineCareKnowledgeAssistant: builder.mutation<MineCareKnowledgeAnswer, { question: string }>({
      query: (payload) => ({ url: `${endpoint}/knowledge/ask`, method: 'POST', data: payload }),
      transformResponse: data<MineCareKnowledgeAnswer>,
    }),
    getMineCareVendorSlas: builder.query<MineCareVendorSla[], void>({
      query: () => ({ url: `${endpoint}/vendor-sla` }),
      transformResponse: data<MineCareVendorSla[]>,
      providesTags: ['MineCareAi'],
    }),
    getMineCareVendorSlaScorecard: builder.query<MineCareVendorSlaScorecard, void>({
      query: () => ({ url: `${endpoint}/vendor-sla/scorecard` }),
      transformResponse: data<MineCareVendorSlaScorecard>,
      providesTags: ['MineCareAi'],
    }),
    createMineCareVendorSla: builder.mutation<MineCareVendorSla, Partial<MineCareVendorSla>>({
      query: (payload) => ({ url: `${endpoint}/vendor-sla`, method: 'POST', data: payload }),
      transformResponse: data<MineCareVendorSla>,
      invalidatesTags: ['MineCareAi'],
    }),
    updateMineCareVendorSla: builder.mutation<MineCareVendorSla, { id: string; data: Partial<MineCareVendorSla> }>({
      query: ({ id, data: payload }) => ({ url: `${endpoint}/vendor-sla/${encodeURIComponent(id)}`, method: 'PUT', data: payload }),
      transformResponse: data<MineCareVendorSla>,
      invalidatesTags: ['MineCareAi'],
    }),
    deleteMineCareVendorSla: builder.mutation<{ id: string }, string>({
      query: (id) => ({ url: `${endpoint}/vendor-sla/${encodeURIComponent(id)}`, method: 'DELETE' }),
      transformResponse: data<{ id: string }>,
      invalidatesTags: ['MineCareAi'],
    }),
    getMineCareRepairReplaceAnalyses: builder.query<MineCareRepairReplaceAnalysis[], void>({
      query: () => ({ url: `${endpoint}/repair-replace` }),
      transformResponse: data<MineCareRepairReplaceAnalysis[]>,
      providesTags: ['MineCareAi'],
    }),
    analyzeMineCareRepairReplace: builder.mutation<MineCareRepairReplaceAnalysis, { equipmentId: string; repairCost?: number; replacementCost?: number }>({
      query: (payload) => ({ url: `${endpoint}/repair-replace/analyze`, method: 'POST', data: payload }),
      transformResponse: data<MineCareRepairReplaceAnalysis>,
      invalidatesTags: ['MineCareAi'],
    }),
    getMineCareDowntimeScenarios: builder.query<MineCareDowntimeScenario[], void>({
      query: () => ({ url: `${endpoint}/downtime/scenarios` }),
      transformResponse: data<MineCareDowntimeScenario[]>,
      providesTags: ['MineCareAi'],
    }),
    simulateMineCareDowntime: builder.mutation<MineCareDowntimeScenario, Partial<MineCareDowntimeScenario>>({
      query: (payload) => ({ url: `${endpoint}/downtime/simulate`, method: 'POST', data: payload }),
      transformResponse: data<MineCareDowntimeScenario>,
      invalidatesTags: ['MineCareAi'],
    }),
    getMineCareTechnicians: builder.query<MineCareTechnician[], void>({
      query: () => ({ url: `${endpoint}/workforce` }),
      transformResponse: data<MineCareTechnician[]>,
      providesTags: ['MineCareAi'],
    }),
    recommendMineCareTechnician: builder.mutation<MineCareTechnician[], { issueType: string; equipmentType: string }>({
      query: (payload) => ({ url: `${endpoint}/workforce/recommend`, method: 'POST', data: payload }),
      transformResponse: data<MineCareTechnician[]>,
    }),
    createMineCareTechnician: builder.mutation<MineCareTechnician, Partial<MineCareTechnician>>({
      query: (payload) => ({ url: `${endpoint}/workforce`, method: 'POST', data: payload }),
      transformResponse: data<MineCareTechnician>,
      invalidatesTags: ['MineCareAi'],
    }),
    updateMineCareTechnician: builder.mutation<MineCareTechnician, { id: string; data: Partial<MineCareTechnician> }>({
      query: ({ id, data: payload }) => ({ url: `${endpoint}/workforce/${encodeURIComponent(id)}`, method: 'PUT', data: payload }),
      transformResponse: data<MineCareTechnician>,
      invalidatesTags: ['MineCareAi'],
    }),
    deleteMineCareTechnician: builder.mutation<{ id: string }, string>({
      query: (id) => ({ url: `${endpoint}/workforce/${encodeURIComponent(id)}`, method: 'DELETE' }),
      transformResponse: data<{ id: string }>,
      invalidatesTags: ['MineCareAi'],
    }),
    getMineCareProcurementOptions: builder.query<MineCareProcurementOption[], void>({
      query: () => ({ url: `${endpoint}/procurement-options` }),
      transformResponse: data<MineCareProcurementOption[]>,
      providesTags: ['MineCareAi'],
    }),
    createMineCareProcurementOption: builder.mutation<MineCareProcurementOption, Partial<MineCareProcurementOption>>({
      query: (payload) => ({ url: `${endpoint}/procurement-options`, method: 'POST', data: payload }),
      transformResponse: data<MineCareProcurementOption>,
      invalidatesTags: ['MineCareAi'],
    }),
    updateMineCareProcurementOption: builder.mutation<MineCareProcurementOption, { id: string; data: Partial<MineCareProcurementOption> }>({
      query: ({ id, data: payload }) => ({ url: `${endpoint}/procurement-options/${encodeURIComponent(id)}`, method: 'PUT', data: payload }),
      transformResponse: data<MineCareProcurementOption>,
      invalidatesTags: ['MineCareAi'],
    }),
    deleteMineCareProcurementOption: builder.mutation<{ id: string }, string>({
      query: (id) => ({ url: `${endpoint}/procurement-options/${encodeURIComponent(id)}`, method: 'DELETE' }),
      transformResponse: data<{ id: string }>,
      invalidatesTags: ['MineCareAi'],
    }),
    getMineCareProcurementComparisons: builder.query<MineCareProcurementComparison[], void>({
      query: () => ({ url: `${endpoint}/procurement-options/comparisons` }),
      transformResponse: data<MineCareProcurementComparison[]>,
      providesTags: ['MineCareAi'],
    }),
    compareMineCareProcurementOptions: builder.mutation<MineCareProcurementComparison, { optionIds?: string[] }>({
      query: (payload) => ({ url: `${endpoint}/procurement-options/compare`, method: 'POST', data: payload }),
      transformResponse: data<MineCareProcurementComparison>,
      invalidatesTags: ['MineCareAi'],
    }),
  }),
})

export const {
  useAnalyzeMineCareRepairReplaceMutation,
  useAnalyzeMineCareRootCauseMutation,
  useAskMineCareCopilotMutation,
  useAskMineCareKnowledgeAssistantMutation,
  useCompareMineCareProcurementOptionsMutation,
  useCreateMineCareProcurementOptionMutation,
  useCreateMineCareEquipmentMutation,
  useCreateMineCareObservationMutation,
  useCreateMineCareTechnicianMutation,
  useCreateMineCareVendorSlaMutation,
  useDeleteMineCareProcurementOptionMutation,
  useDeleteMineCareTechnicianMutation,
  useDeleteMineCareVendorSlaMutation,
  useDeleteMineCareEquipmentMutation,
  useExtractMineCareEquipmentDocumentsMutation,
  useGenerateMineCareChecklistMutation,
  useGenerateMineCareExecutiveReportMutation,
  useGetMineCareActionCenterQuery,
  useGetMineCareAlertsQuery,
  useGetMineCareBudgetForecastQuery,
  useGetMineCareChecklistsQuery,
  useGetMineCareDashboardSummaryQuery,
  useGetMineCareDowntimeScenariosQuery,
  useGetMineCareEquipmentDetailsQuery,
  useGetMineCareEquipmentQuery,
  useGetMineCareKnowledgeDocumentsQuery,
  useGetMineCareObservationsQuery,
  useGetMineCareProcurementOptionsQuery,
  useGetMineCareProcurementComparisonsQuery,
  useGetMineCareRecommendationsQuery,
  useGetMineCareRepairReplaceAnalysesQuery,
  useGetMineCareRiskRankingQuery,
  useGetMineCareRootCausesQuery,
  useGetMineCareServiceCalendarQuery,
  useGetMineCareSparePartsQuery,
  useGetMineCareTechniciansQuery,
  useGetMineCareVendorSlaScorecardQuery,
  useGetMineCareVendorSlasQuery,
  useGetMineCareWarrantyAlertsQuery,
  useGetMineCareWarrantyClaimsQuery,
  useRecommendMineCareTechnicianMutation,
  useCompleteMineCareServiceMutation,
  useRecordMineCareBreakdownRepairMutation,
  useSimulateMineCareDowntimeMutation,
  useUpdateMineCareActionStatusMutation,
  useUpdateMineCareAlertStatusMutation,
  useUpdateMineCareChecklistItemMutation,
  useUpdateMineCareEquipmentMutation,
  useUpdateMineCareProcurementOptionMutation,
  useUpdateMineCareRecommendationStatusMutation,
  useUpdateMineCareTechnicianMutation,
  useUpdateMineCareVendorSlaMutation,
  useUpdateMineCareWarrantyClaimStatusMutation,
  useUploadMineCareKnowledgeDocumentMutation,
} = mineCareAiApi
