import {
  BadgeDollarSign,
  Banknote,
  Ban,
  BarChart3,
  Bot,
  BookOpen,
  Brain,
  BrainCircuit,
  Briefcase,
  BriefcaseBusiness,
  BriefcaseMedical,
  Building2,
  Calendar,
  CalendarDays,
  CheckCircle,
  CheckSquare,
  Circle,
  CircleDollarSign,
  Clock3,
  ClipboardCheck,
  ClipboardList,
  Code,
  CreditCard,
  DollarSign,
  Edit,
  FileCheck2,
  FileSearch,
  FileText,
  FileX2,
  FolderArchive,
  FolderOpen,
  Gavel,
  Gauge,
  HandCoins,
  Handshake,
  History,
  Hospital,
  Landmark,
  LayoutDashboard,
  Link,
  ListOrdered,
  ListTodo,
  Lock,
  Menu,
  MousePointer,
  PieChart,
  PlusCircle,
  PlugZap,
  ReceiptText,
  RefreshCcw,
  Repeat2,
  Scale,
  ScrollText,
  SearchCheck,
  Send,
  Megaphone,
  ServerCog,
  Settings,
  ShieldCheck,
  Stethoscope,
  Undo2,
  Upload,
  UserPlus,
  UserRound,
  UserRoundCheck,
  UserRoundCog,
  Users,
  WalletCards,
  XCircle,
  Activity,
  Layers,
  Scroll,
  ShieldAlert,
  ShoppingCart,
  Trash2,
  TimerReset,
  UserCheck,
  AppWindow,
  CloudUpload,
  GitCommit,
  KeyRound,
  Server,
  Rocket
} from 'lucide-react'

import type { LucideIcon } from 'lucide-react'

const menuIconMap: Record<string, LucideIcon> = {
  activities: ClipboardList,
  adjustment: ReceiptText,
  adjustments: ReceiptText,
  'appeal': FileCheck2,
  appeals: FileCheck2,
  appointment: CalendarDays,
  appointments: CalendarDays,
  'app-window': AppWindow,
  'ar-work-items': ClipboardList,
  'ar-work-queue': ClipboardList,
  'audit-log': ScrollText,
  'audit-logs': ScrollText,
  'badge-dollar-sign': BadgeDollarSign,
  banknote: Banknote,
  ban: Ban,
  'bar-chart': BarChart3,
  'bar-chart-3': BarChart3,
  bot: Bot,
  briefcase: Briefcase,
  'briefcase-business': BriefcaseBusiness,
  'briefcase-medical': BriefcaseMedical,
  calendar: Calendar,
  'charge-capture': ReceiptText,
  'charge-master': BadgeDollarSign,
  'charge-masters': BadgeDollarSign,
  charges: ReceiptText,
  'check-circle': CheckCircle,
  'check-square': CheckSquare,
  'claim-ai-review': SearchCheck,
  'claim-ai-reviews': SearchCheck,
  'claim-creation': FileText,
  'claim-submission': Send,
  'claim-submissions': Send,
  'claim-tracking': ClipboardCheck,
  'claim-tracking-rejections': ClipboardCheck,
  'claim-trackings': ClipboardCheck,
  claims: FileText,
  circle: Circle,
  'cloud-upload': CloudUpload,
  'clipboard-list': ClipboardList,
  code: Code,
  'coding-review': FileCheck2,
  'coding-review-scrubbing': FileCheck2,
  'coding-reviews': FileCheck2,
  compliance: ShieldCheck,
  compliances: ShieldCheck,
  collection: FolderArchive,
  collections: FolderArchive,
  'corrected-claim': Repeat2,
  'corrected-claims': Repeat2,
  'coverage-rule': ShieldCheck,
  'coverage-rules': ShieldCheck,
  'credit-card': CreditCard,
  denial: FileX2,
  denials: FileX2,
  'dollar-sign': DollarSign,
  document: FolderOpen,
  'documentation-compliance-alert': FileSearch,
  'documentation-compliance-alerts': FileSearch,
  documents: FolderOpen,
  edit: Edit,
  'eligibility-verification': SearchCheck,
  'eligibility-verifications': SearchCheck,
  encounter: ClipboardList,
  encounters: ClipboardList,
  'era-eob-processing': FileCheck2,
  'era-eob-processings': FileCheck2,
  facilities: Hospital,
  facility: Hospital,
  'fee-schedule': BadgeDollarSign,
  'fee-schedules': BadgeDollarSign,
  'file-alt': FileText,
  'file-check': FileCheck2,
  'file-check-2': FileCheck2,
  'file-medical': FileText,
  'file-search': FileSearch,
  'file-text': FileText,
  'file-x': FileX2,
  'file-x-2': FileX2,
  'folder-archive': FolderArchive,
  'folder-open': FolderOpen,
  gavel: Gavel,
  'git-commit': GitCommit,
  'hand-coins': HandCoins,
  history: History,
  hospital: Hospital,
  'building-user': Building2,
  building: Building2,
  'building-2': Building2,
  'insurance-management': ShieldCheck,
  'insurance-policies': ShieldCheck,
  'insurance-policy': ShieldCheck,
  landmark: Landmark,
  'key-round': KeyRound,
  dashboard: LayoutDashboard,
  link: Link,
  'interested-topic': ListTodo,
  'interested-topics': ListTodo,
  layers: Layers,
  'layout-dashboard': LayoutDashboard,
  'list-ol': ListOrdered,
  megaphone: Megaphone,
  'list-todo': ListTodo,
  'action-center': ListTodo,
  alerts: ShieldAlert,
  'ai-copilot': Bot,
  'asset-passport': ClipboardCheck,
  'budget-forecast': BadgeDollarSign,
  'equipment-onboarding': PlusCircle,
  'equipment-registry': ClipboardList,
  minecare: Activity,
  'minecare-ai': Activity,
  'operator-observations': ClipboardList,
  'risk-ranking': BarChart3,
  'service-calendar': CalendarDays,
  'spare-parts-planner': Layers,
  spares: Layers,
  'warranty-tracker': ShieldCheck,
  checklists: ClipboardCheck,
  'downtime-simulator': TimerReset,
  'knowledge-assistant': BookOpen,
  'procurement-advisor': ShoppingCart,
  'ai-recommendations': BrainCircuit,
  'repair-replace': RefreshCcw,
  'root-cause-analysis': BrainCircuit,
  'sensor-ml': Gauge,
  'vendor-sla': Handshake,
  'workforce-advisor': UserCheck,
  lock: Lock,
  menu: Menu,
  menus: Menu,
  'mouse-pointer': MousePointer,
  'patient-billing': WalletCards,
  'patient-billings': WalletCards,
  'patient-payment': HandCoins,
  'patient-payments': HandCoins,
  patients: Users,
  payer: Landmark,
  payers: Landmark,
  'payment-posting': CircleDollarSign,
  'payment-postings': CircleDollarSign,
  'pie-chart': PieChart,
  'plus-circle': PlusCircle,
  'plug-zap': PlugZap,
  provider: Stethoscope,
  providers: Stethoscope,
  'prior-authorization': ClipboardCheck,
  'prior-authorizations': ClipboardCheck,
  receipt: ReceiptText,
  'receipt-text': ReceiptText,
  referral: Repeat2,
  referrals: Repeat2,
  refund: RefreshCcw,
  refunds: RefreshCcw,
  report: BarChart3,
  reports: BarChart3,
  'reports-analytics': BarChart3,
  'roles': ShieldCheck,
  remediation: ShieldCheck,
  rcm: BriefcaseBusiness,
  'server-cog': ServerCog,
  server: Server,
  'scan-results': ShieldCheck,
  scroll: Scroll,
  activity: Activity,
  'scroll-text': ScrollText,
  scale: Scale,
  'search-dollar': SearchCheck,
  'search-check': SearchCheck,
  send: Send,
  settings: Settings,
  shield: ShieldCheck,
  'shield-check': ShieldCheck,
  'shield-alert': ShieldAlert,
  stethoscope: Stethoscope,
  task: ListTodo,
  tasks: ListTodo,
  'timely-filing': Clock3,
  'timely-filing-alert': Clock3,
  'timely-filing-alerts': Clock3,
  'trash-2': Trash2,
  'tasks-work-queue': ListTodo,
  undo: Undo2,
  upload: Upload,
  user: UserRound,
  'user-md': Stethoscope,
  'user-plus': UserPlus,
  'user-round': UserRound,
  'user-round-check': UserRoundCheck,
  'user-round-cog': UserRoundCog,
  users: Users,
  wallet: WalletCards,
  'wallet-cards': WalletCards,
  'x-circle': XCircle,
  brain: Brain,
  rocket: Rocket
}

function normalizeIconKey(value?: string) {
  const trimmedValue = value?.trim()

  if (!trimmedValue) {
    return ''
  }

  const lastRouteSegment = trimmedValue.split('/').filter(Boolean).at(-1) ?? trimmedValue

  return lastRouteSegment
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

export function resolveMenuIcon(iconName?: string): LucideIcon {
  const normalizedIconName = normalizeIconKey(iconName)

  if (!normalizedIconName) {
    return Circle
  }

  return menuIconMap[normalizedIconName] ?? Circle
}
