"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: list[str] | None = None) -> list[str]:
    value = os.getenv(name)
    if value is None:
        return list(default or [])
    return [item.strip() for item in value.split(",") if item.strip()]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add apps directory to sys.path
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Load environment variables
dotenv_override = os.getenv("DOTENV_PATH")
if dotenv_override:
    load_dotenv(dotenv_override)
else:
    for candidate in (BASE_DIR / ".env", BASE_DIR / ".env.local"):
        if candidate.is_file():
            load_dotenv(candidate)
            break

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-gd=8)9um-*0g%vfzd!26tnon5l)m^di874(6#$m!b9$67n9v!2')
AGENTIC_SERVER_API_KEY = os.getenv('AGENTIC_SERVER_API_KEY', 'change-me-shared-rcm-ai-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', False)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', ['localhost', '127.0.0.1', '[::1]'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'corsheaders',
    'ninja',
    
    # Internal apps
    'agents.apps.AgentsConfig',
    'api.apps.ApiConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Priority for CORS
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middleware.APILoggingMiddleware',  # Custom middleware for API logging
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Increase payload size limits for large server scans (10MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760

# CORS Settings
DEFAULT_LOCAL_CORS_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
CORS_ALLOW_ALL_ORIGINS = env_bool('CORS_ALLOW_ALL_ORIGINS', False)
CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    DEFAULT_LOCAL_CORS_ORIGINS if DEBUG else []
)
CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    CORS_ALLOWED_ORIGINS
)

# --- CrewAI & LLM Settings ---
LLM_PROVIDER = os.getenv("CREWAI_CONTENT_LLM_PROVIDER", "ollama").strip().lower()
LLM_MODEL = os.getenv("CREWAI_CONTENT_LLM_MODEL", "")
OPENAI_API_KEY = os.getenv("CREWAI_CONTENT_OPENAI_API_KEY", os.getenv("OPENAI_API_KEY"))
OPENAI_BASE_URL = os.getenv("CREWAI_CONTENT_OPENAI_BASE_URL", None)
OPENAI_WEB_SEARCH_MODEL = os.getenv("CREWAI_CONTENT_OPENAI_WEB_SEARCH_MODEL", "gpt-5.5")
OLLAMA_BASE_URL = os.getenv("CREWAI_CONTENT_OLLAMA_BASE_URL", "http://localhost:11434")
OLLAMA_MODEL = os.getenv("CREWAI_CONTENT_OLLAMA_MODEL", "ollama/gpt-oss:120b-cloud")
OLLAMA_TEMPERATURE = float(os.getenv("CREWAI_CONTENT_OLLAMA_TEMPERATURE", 0.4))
OLLAMA_TIMEOUT = int(os.getenv("CREWAI_CONTENT_OLLAMA_TIMEOUT", 600))
MAINTENANCE_CREWAI_ENABLED = os.getenv("MAINTENANCE_CREWAI_ENABLED", "False") == "True"
CREWAI_VERBOSE = env_bool("CREWAI_VERBOSE", False)

# Search & Research
MAX_SEARCH_RESULTS = int(os.getenv("CREWAI_CONTENT_MAX_SEARCH_RESULTS", 5))
MAX_SCRAPE_SOURCES = int(os.getenv("CREWAI_CONTENT_MAX_SCRAPE_SOURCES", 4))
MAX_CHARS_PER_SOURCE = int(os.getenv("CREWAI_CONTENT_MAX_CHARS_PER_SOURCE", 6000))
REQUEST_TIMEOUT_SECONDS = int(os.getenv("CREWAI_CONTENT_REQUEST_TIMEOUT", 600))
USER_AGENT = os.getenv("CREWAI_CONTENT_USER_AGENT", "Mozilla/5.0")

# Google CSE
GOOGLE_CSE_API_KEY = os.getenv("GOOGLE_CSE_API_KEY")
GOOGLE_CSE_ID = os.getenv("GOOGLE_CSE_ID")
YOUTUBE_DATA_API_KEY = os.getenv("YOUTUBE_DATA_API_KEY")
X_BEARER_TOKEN = os.getenv("X_BEARER_TOKEN")

# MongoDB Fallback (If still used by research scripts)
MONGO_URI = os.getenv("CREWAI_CONTENT_MONGO_URI")
MONGO_DB_NAME = os.getenv("CREWAI_CONTENT_MONGO_DB")
MONGO_OUTPUT_COLL = os.getenv("CREWAI_CONTENT_OUTPUT_COLLECTION", "generated_content_runs")
SAVE_RESULT_DEFAULT = os.getenv("CREWAI_CONTENT_SAVE_RESULT", "True") == "True"
MARK_TOPIC_PROCESSED_DEFAULT = os.getenv("CREWAI_CONTENT_MARK_TOPIC_PROCESSED", "True") == "True"

# --- Logging Configuration ---
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'apps': {  # Logger for our internal apps
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'api.requests': {  # Logger for API requests/responses
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.api': {  # Logger for API app
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'agents': {  # Logger for research and scraping
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'crewai': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'litellm': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
